name: biology_fun
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  cached_network_image: 3.2.3
  cupertino_icons: ^1.0.2
  dropdown_search: ^5.0.6
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.7.2+3
  flutter_jigsaw_puzzle: ^0.1.0
  get: 4.6.5
  get_storage: ^2.1.1
  google_fonts: ^4.0.3
  http: 0.13.5
  introduction_screen: ^3.1.8
  just_audio: ^0.9.32
  lottie: ^2.3.2
  mobile_scanner: ^3.2.0
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
