name: biology_fun
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  cached_network_image: 3.2.3
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: ^4.0.3
  http: 0.13.5
  copy_with_extension_gen: 5.0.2
  build_runner: 2.3.3
  im_stepper: 1.0.1+1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

